### PR TITLE
Fixed the utc_from_timestamp method ,added test cases

### PR DESCRIPTION
**Pull request by shubhamdixit863**
This Pr fixes the issue 

https://github.com/numaproj/numaflow-rs/issues/59

### CODE REVIEW

**Review by KeranYang — COMMENTED** [review]
LGTM. I think @vigith asked for epoch(0) test. Could you add?

**Comment by yhl25** [comment]
```
pub(crate) fn utc_from_timestamp(t: Option<Timestamp>) -> DateTime<Utc> {
    t.map_or(Utc.timestamp_nanos(-1), |t| {
        DateTime::from_timestamp(t.seconds, t.nanos as u32).unwrap_or(Utc.timestamp_nanos(-1))
    })
}
``` 
use this, I have already fixed this issue in my [PR](https://github.com/numaproj/numaflow-rs/blob/75534f1c0e1287fbeabec8659b94d5f17a05fa25/src/shared.rs#L45)

**Review by yhl25 — COMMENTED** [review]
```
pub(crate) fn utc_from_timestamp(t: Option<Timestamp>) -> DateTime<Utc> {
    t.map_or(Utc.timestamp_nanos(-1), |t| {
        DateTime::from_timestamp(t.seconds, t.nanos as u32).unwrap_or(Utc.timestamp_nanos(-1))
    })
}
``` 
use this, I have already fixed this issue in my [PR](https://github.com/numaproj/numaflow-rs/blob/75534f1c0e1287fbeabec8659b94d5f17a05fa25/src/shared.rs#L45)

**Comment by vigith** [comment]
> ```
> 
> pub(crate) fn utc_from_timestamp(t: Option<Timestamp>) -> DateTime<Utc> {
> 
>     t.map_or(Utc.timestamp_nanos(-1), |t| {
> 
>         DateTime::from_timestamp(t.seconds, t.nanos as u32).unwrap_or(Utc.timestamp_nanos(-1))
> 
>     })
> 
> }
> 
> ``` 

This is the right way to do, mathematical operations shouldn't be done directly on time

**Comment by shubhamdixit863** [comment]
> ```
> pub(crate) fn utc_from_timestamp(t: Option<Timestamp>) -> DateTime<Utc> {
>     t.map_or(Utc.timestamp_nanos(-1), |t| {
>         DateTime::from_timestamp(t.seconds, t.nanos as u32).unwrap_or(Utc.timestamp_nanos(-1))
>     })
> }
> ```
> 
> use this, I have already fixed this issue in my [PR](https://github.com/numaproj/numaflow-rs/blob/75534f1c0e1287fbeabec8659b94d5f17a05fa25/src/shared.rs#L45)

ok

**Review by yhl25 — APPROVED** [review]

**Pull request merged**
